name: Workflow

on:
  # Run on pushes to main..
  push:
    branches:
      - main
  # ..and any pull request.
  pull_request:

jobs:
  unit:
    name: unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: 24.13.1
      - run: yarn
      - run: yarn test
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v2
        with:
          path: coverage/lcov-report
      - name: 'Upload coverage to Codecov'
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: 24.13.1
      - run: yarn
      - run: yarn lint
